services:
  iview_nginx:
    image: ghcr.io/malteeez/cato_bot:main
    container_name: discord_cato_bot
    restart: always
    environment:
      - BOT_TOKEN=YOUR-BOT-TOKEN
      - BOT_ID=YOUR-BOT-CLIENT-ID